version: '3.7'
services:

  db:
    image: mysql/mysql-server:5.7
    container_name: db_express
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password 
      MYSQL_DATABASE: app_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: password_here
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3318:3306" #outside:inside docker container from-within
